# Generated by Django 5.2.17 on 2026-09-29 21:24

import django.db.models.deletion
import orders.storage
import uuid
from django.conf import settings
from django.db import migrations, models


def initialize_existing_orders(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    references = set()
    for order in Order.objects.order_by('pk').iterator():
        key = f'{order.payment_method}:{order.transaction_reference.strip().upper()}'
        order.tracking_token = uuid.uuid4()
        # Existing duplicate references remain readable, but cannot be submitted again.
        if key not in references:
            order.payment_reference_key = key
            references.add(key)
        order.save(update_fields=['tracking_token', 'payment_reference_key'])
    for item in OrderItem.objects.select_related('product').iterator():
        item.product_name = item.product.name
        item.color = item.product.color
        item.save(update_fields=['product_name', 'color'])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_coupon_order_discount_amount_order_subtotal"),
        ("products", "0004_storesettings_alter_product_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="checkout_key",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("completed", "Completed"),
                ],
                default="processing",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference_key",
            field=models.CharField(
                editable=False, max_length=220, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_token",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt_url",
            field=models.ImageField(
                storage=orders.storage.ReceiptStorage(),
                upload_to=orders.storage.receipt_path,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.product"
            ),
        ),
        migrations.RunPython(initialize_existing_orders, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="OrderEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("received", "Received"), ("decision", "Decision")],
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "kind"), name="one_order_email_per_kind"
                    )
                ],
            },
        ),
    ]
