# Generated by Django 5.2.17 on 2026-09-29 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_storesettings_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color_hex",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$",
                        "Use a six-digit hex color, such as #b4a0d2.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="style",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Products with the same style are linked as color options.",
            ),
        ),
    ]
