# Generated by Django 5.2.17 on 2026-09-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_color_hex_product_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="telegram_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="tiktok_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
