# Generated by Django 5.2.17 on 2026-09-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="announcement",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="coupon",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
